name: Build and test

# on: [push]

on:
  push:
  # branches-ignore: "dependabot/**"
  # pull_request:
  #   paths-ignore:
  #     - "**.md"
  schedule:
    - cron: "0 6 * * 3"

jobs:
  build-test-staticcheck:
    name: Build, Test and Check
    runs-on: ubuntu-latest
    # env:
    #   BUTLER_DEBUG: true
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Restore Cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/go/pkg
          key: 1.19-${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Get butler
        run: |
          go get github.com/robertranjan/butler
          go install github.com/robertranjan/butler
          echo "-----------------------------"
          which butler
          butler help
          echo "-----------------------------"
          butler version

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          echo "-------- env start -----------"
          env
          echo "-------- lets start build the application -----------"
          butler build
        env:
          BUTLER_DEBUG: true

      - name: Test
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          butler test

      - name: Staticcheck
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          butler staticcheck
